[project]
authors = ["Haardik H"]
entry = "main.sw"
license = "Apache-2.0"
name = "fuel-badges"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.1" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.20.1" }
